#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD9631FEAF0CC6227 (infra-root@openstack.org)
#
Name     : python-heatclient
Version  : 1.5.0
Release  : 32
URL      : http://tarballs.openstack.org/python-heatclient/python-heatclient-1.5.0.tar.gz
Source0  : http://tarballs.openstack.org/python-heatclient/python-heatclient-1.5.0.tar.gz
Source99 : http://tarballs.openstack.org/python-heatclient/python-heatclient-1.5.0.tar.gz.asc
Summary  : OpenStack Orchestration API Client Library
Group    : Development/Tools
License  : Apache-2.0
Requires: python-heatclient-bin
Requires: python-heatclient-python
Requires: Babel
Requires: PyYAML
Requires: cliff
Requires: iso8601
Requires: keystoneauth1
Requires: osc-lib
Requires: oslo.i18n
Requires: oslo.serialization
Requires: oslo.utils
Requires: pbr
Requires: python-swiftclient
Requires: requests
Requires: six
BuildRequires : configparser-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
=================
python-heatclient
=================
.. image:: https://img.shields.io/pypi/v/python-heatclient.svg
:target: https://pypi.python.org/pypi/python-heatclient/
:alt: Latest Version

%package bin
Summary: bin components for the python-heatclient package.
Group: Binaries

%description bin
bin components for the python-heatclient package.


%package python
Summary: python components for the python-heatclient package.
Group: Default

%description python
python components for the python-heatclient package.


%prep
%setup -q -n python-heatclient-1.5.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489336269
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489336269
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/heat

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
