#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : python-heatclient
Version  : 1.16.0
Release  : 36
URL      : http://tarballs.openstack.org/python-heatclient/python-heatclient-1.16.0.tar.gz
Source0  : http://tarballs.openstack.org/python-heatclient/python-heatclient-1.16.0.tar.gz
Source99 : http://tarballs.openstack.org/python-heatclient/python-heatclient-1.16.0.tar.gz.asc
Summary  : OpenStack Orchestration API Client Library
Group    : Development/Tools
License  : Apache-2.0
Requires: python-heatclient-bin
Requires: python-heatclient-python3
Requires: python-heatclient-license
Requires: python-heatclient-python
Requires: Babel
Requires: PyYAML
Requires: Sphinx
Requires: cliff
Requires: iso8601
Requires: keystoneauth1
Requires: openstackdocstheme
Requires: osc-lib
Requires: oslo.i18n
Requires: oslo.serialization
Requires: oslo.utils
Requires: pbr
Requires: python-swiftclient
Requires: reno
Requires: requests
Requires: six
Requires: sphinxcontrib-httpdomain
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Team and repository tags
        ========================

%package bin
Summary: bin components for the python-heatclient package.
Group: Binaries
Requires: python-heatclient-license

%description bin
bin components for the python-heatclient package.


%package license
Summary: license components for the python-heatclient package.
Group: Default

%description license
license components for the python-heatclient package.


%package python
Summary: python components for the python-heatclient package.
Group: Default
Requires: python-heatclient-python3

%description python
python components for the python-heatclient package.


%package python3
Summary: python3 components for the python-heatclient package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-heatclient package.


%prep
%setup -q -n python-heatclient-1.16.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532381666
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/python-heatclient
cp LICENSE %{buildroot}/usr/share/doc/python-heatclient/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/heat

%files license
%defattr(-,root,root,-)
/usr/share/doc/python-heatclient/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
